### PR TITLE
Snippet lib release v1.2.0.

### PR DESCRIPTION
**Pull request by adorokhine**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-snippet-lib/63)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG, line 2 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/63#-Kl24Y7RIq7MmqDVJmhA:-Kl24Y7RIq7MmqDVJmhB:b-kdbpq9) ([raw file](https://github.com/google/mobly-snippet-lib/blob/6616029943602f43439b18d56359db92422a66b3/CHANGELOG#L2)):*
> ```
> 1.2.0:
>   - Snippet protocol is now versionated
> ```

should the first one be the new version of the launch protocol?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/63)*

**Comment by adorokhine** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG, line 2 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/63#-Kl24Y7RIq7MmqDVJmhA:-Kl6Hr1usuciOw5r0GDL:braxjuv) ([raw file](https://github.com/google/mobly-snippet-lib/blob/6616029943602f43439b18d56359db92422a66b3/CHANGELOG#L2)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

should the first one be the new version of the launch protocol?
</blockquote></details>

I'm not quite sure what this comment means but I changed the changelog around a bit, lmk

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/63)*

**Comment by xpconanfan** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG, line 2 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/63#-Kl24Y7RIq7MmqDVJmhA:-KlMHvK1KF3vcg1nsSoY:b14x6j0) ([raw file](https://github.com/google/mobly-snippet-lib/blob/6616029943602f43439b18d56359db92422a66b3/CHANGELOG#L2)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

I'm not quite sure what this comment means but I changed the changelog around a bit, lmk
</blockquote></details>

should we explicitly mention that this version includes a new startup protocol?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/63)*

**Comment by adorokhine** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG, line 2 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/63#-Kl24Y7RIq7MmqDVJmhA:-KlQONelAX_AupVRF9hT:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/6616029943602f43439b18d56359db92422a66b3/CHANGELOG#L2)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

should we explicitly mention that this version includes a new startup protocol?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/63)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/63#-:-KlQQfNlJgOj3Sl_k5tf:bnfp4nl)*

**Pull request merged**
