### PR TITLE
Fix exception handling in snippets.

### PR DESCRIPTION
**Pull request by adorokhine**
* Don't try to call methods on snippet classes that couldn't be constructed
* Don't obscure the cause of exceptions
* Propagate the entire stack trace to the python side

### CODE REVIEW

**Comment by xpconanfan** [comment]
Do we want to print the whole thing?
We used to only print the final (or first depending on which direction you count from) line of the stacktrace.
The python side would already have a stacktrace from the python exception, wouldn't mixing in the java stacktrace make it hard to read?

**Comment by adorokhine** [comment]
How do you figure out where in the snippet code your exception came from?

**Comment by xpconanfan** [comment]
Previously the standard way was to look at logcat, which should have the full stacktrace and more about the crash.

Printing the java side stacktrace in test details on python side could be done if we format things carefully. If I were debugging and an exception happened on Java side, I usually would go to logcat logs anyway since it has more info to work with for java-side debugging in general.

**Comment by adorokhine** [comment]
Do we want that though? Now users are writing code on both sides of the snippet. We've already had confusion due to missing/bare exceptions making it hard for people to debug their snippet code/figure out what the issue was.

The formatting isn't too bad:
```
Connected to NP5A3B0090.
Call methods against:
    ad (android_device.AndroidDevice)
    snippet or s (Snippet)
>>> s.throwSomething()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/google/home/adorokhine/work/mobly.git/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 292, in rpc_call
    return self._rpc(name, *args)
  File "/usr/local/google/home/adorokhine/work/mobly.git/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 270, in _rpc
    raise ApiError(result['error'])
ApiError: java.lang.UnsupportedOperationException: x
        at com.google.android.mobly.snippet.example1.ExampleSnippet2.<init>(ExampleSnippet2.java:25)
        at java.lang.reflect.Constructor.newInstance0(Native Method)                                                                                                                                                                                          
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)                                                                                                                                                                                    
        at com.google.android.mobly.snippet.manager.SnippetManager.get(SnippetManager.java:104)                                                                                                                                                               
        at com.google.android.mobly.snippet.manager.SnippetManager.invoke(SnippetManager.java:77)                                                                                                                                                             
        at com.google.android.mobly.snippet.rpc.MethodDescriptor.invoke(MethodDescriptor.java:91)                                                                                                                                                             
        at com.google.android.mobly.snippet.rpc.JsonRpcServer.handleRPCConnection(JsonRpcServer.java:109)                                                                                                                                                     
        at com.google.android.mobly.snippet.rpc.SimpleServer$ConnectionThread.run(SimpleServer.java:110)                                                                                                                                                      
                                                                                                                                                                                                                                                              
>>>   
```

**Comment by adorokhine** [comment]
And an example from an actual exception thrown by a method:

```
>>> s.throwSomething()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/google/home/adorokhine/work/mobly.git/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 292, in rpc_call
    return self._rpc(name, *args)
  File "/usr/local/google/home/adorokhine/work/mobly.git/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 270, in _rpc
    raise ApiError(result['error'])
ApiError: java.io.IOException: Example exception from throwSomething()
        at com.google.android.mobly.snippet.example1.ExampleSnippet2.throwSomething(ExampleSnippet2.java:31)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.google.android.mobly.snippet.manager.SnippetManager.invoke(SnippetManager.java:78)
        at com.google.android.mobly.snippet.rpc.MethodDescriptor.invoke(MethodDescriptor.java:91)
        at com.google.android.mobly.snippet.rpc.JsonRpcServer.handleRPCConnection(JsonRpcServer.java:108)
        at com.google.android.mobly.snippet.rpc.SimpleServer$ConnectionThread.run(SimpleServer.java:110)
```

**Comment by xpconanfan** [comment]
Can we draw a line between the Python trace and the Java trace?

Something like:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/google/home/adorokhine/work/mobly.git/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 292, in rpc_call
    return self._rpc(name, *args)
  File "/usr/local/google/home/adorokhine/work/mobly.git/mobly/controllers/android_device_lib/jsonrpc_client_base.py", line 270, in _rpc
    raise ApiError(result['error'])
------------------ Java stacktrace ------------------
ApiError: java.io.IOException: Example exception from throwSomething()
        at com.google.android.mobly.snippet.example1.ExampleSnippet2.throwSomething(ExampleSnippet2.java:31)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.google.android.mobly.snippet.manager.SnippetManager.invoke(SnippetManager.java:78)
        at com.google.android.mobly.snippet.rpc.MethodDescriptor.invoke(MethodDescriptor.java:91)
        at com.google.android.mobly.snippet.rpc.JsonRpcServer.handleRPCConnection(JsonRpcServer.java:108)
        at com.google.android.mobly.snippet.rpc.SimpleServer$ConnectionThread.run(SimpleServer.java:110)
------------------------------------------------------
```

**Comment by adorokhine** [comment]
Done.

**Pull request merged**
