### PR TITLE
Snippet lib release v1.4.0

### PR DESCRIPTION
**Pull request by ko1in1u**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-snippet-lib/125)

### CODE REVIEW

**Review by xianyuanjia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly-snippet-lib/125)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @ko1in1u and @xpconanfan)

___
*[`third_party/sl4a/gradle.properties` line 3 at r1](https://reviewable.io/reviews/google/mobly-snippet-lib/125#-NV1Fq_gBXceUfb8WiS8:-NV1Fq_gBXceUfb8WiS9:b-jsvvb9) ([raw file](https://github.com/google/mobly-snippet-lib/blob/eda1ecc0e53162d679097ac61467a6854ffdbe7b/third_party/sl4a/gradle.properties#L3)):*
> ```INI
> # This version code implements the versioning recommendations in:
> # https://blog.jayway.com/2015/03/11/automatic-versioncode-generation-in-android-gradle/
> VERSION_CODE=1030200
> ```

update to 1030299 (see https://github.com/google/mobly-snippet-lib/pull/35)

**Comment by ko1in1u** [comment]
> > _[Reviewable](https://reviewable.io/reviews/google/mobly-snippet-lib/125)_ status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @ko1in1u and @xpconanfan)
> 
> _[`third_party/sl4a/gradle.properties` line 3 at r1](https://reviewable.io/reviews/google/mobly-snippet-lib/125#-NV1Fq_gBXceUfb8WiS8:-NV1Fq_gBXceUfb8WiS9:b-jsvvb9) ([raw file](https://github.com/google/mobly-snippet-lib/blob/eda1ecc0e53162d679097ac61467a6854ffdbe7b/third_party/sl4a/gradle.properties#L3)):_
> 
> > ```ini
> > # This version code implements the versioning recommendations in:
> > # https://blog.jayway.com/2015/03/11/automatic-versioncode-generation-in-android-gradle/
> > VERSION_CODE=1030200
> > ```
> 
> update to 1030299 (see #35)

Updated, thank you.

**Comment by ko1in1u** [comment]
Cleaned up TODOs.

**Review by xianyuanjia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly-snippet-lib/125)* status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @ko1in1u and @xpconanfan)

___
*[`CHANGELOG` line 1 at r3](https://reviewable.io/reviews/google/mobly-snippet-lib/125#-NVWXc6zDei4kFnx473I:-NVWXc6zDei4kFnx473J:bkd4xkz) ([raw file](https://github.com/google/mobly-snippet-lib/blob/e681041b0296098de5b92c01cfab47a44c1b7101/CHANGELOG#L1)):*
> ```
> 1.3.2:
> ```

After discussion and resolving TODOs, we should make this 1.4.0?



_Code quote:_
```
1.3.2
```
___
*[`examples/ex1_standalone_app/build.gradle` line 25 at r3](https://reviewable.io/reviews/google/mobly-snippet-lib/125#-NVWXwRi-0a1KegjQ6h5:-NVWXwRi-0a1KegjQ6h6:byr4ffv) ([raw file](https://github.com/google/mobly-snippet-lib/blob/e681041b0296098de5b92c01cfab47a44c1b7101/examples/ex1_standalone_app/build.gradle#L25)):*
> ```Gradle
>     // this repo. For your own snippets, you'll want to use the regular
>     // 'implementation' dep instead:
>     //implementation 'com.google.android.mobly:mobly-snippet-lib:1.3.2'
> ```

see above



_Code quote:_
```Gradle
1.3.2
```
___
*[`third_party/sl4a/gradle.properties` line 3 at r1](https://reviewable.io/reviews/google/mobly-snippet-lib/125#-NV1Fq_gBXceUfb8WiS8:-NVWXy4w7NJll1wx1hSn:b-8jhx0c) ([raw file](https://github.com/google/mobly-snippet-lib/blob/eda1ecc0e53162d679097ac61467a6854ffdbe7b/third_party/sl4a/gradle.properties#L3)):*
<details><summary><i>Previously, ko1in1u (Kolin Lu) wrote…</i></summary><blockquote>

Updated, thank you.
</blockquote></details>

change to 1040099?

**Comment by ko1in1u** [comment]
> > _[Reviewable](https://reviewable.io/reviews/google/mobly-snippet-lib/125)_ status: 0 of 14 files reviewed, 3 unresolved discussions (waiting on @ko1in1u and @xpconanfan)
> 
> _[`CHANGELOG` line 1 at r3](https://reviewable.io/reviews/google/mobly-snippet-lib/125#-NVWXc6zDei4kFnx473I:-NVWXc6zDei4kFnx473J:bkd4xkz) ([raw file](https://github.com/google/mobly-snippet-lib/blob/e681041b0296098de5b92c01cfab47a44c1b7101/CHANGELOG#L1)):_
> 
> > ```
> > 1.3.2:
> > ```
> 
> After discussion and resolving TODOs, we should make this 1.4.0?
> 
> _Code quote:_
> 
> ```
> 1.3.2
> ```
> 
> _[`examples/ex1_standalone_app/build.gradle` line 25 at r3](https://reviewable.io/reviews/google/mobly-snippet-lib/125#-NVWXwRi-0a1KegjQ6h5:-NVWXwRi-0a1KegjQ6h6:byr4ffv) ([raw file](https://github.com/google/mobly-snippet-lib/blob/e681041b0296098de5b92c01cfab47a44c1b7101/examples/ex1_standalone_app/build.gradle#L25)):_
> 
> > ```groovy-gradle
> >     // this repo. For your own snippets, you'll want to use the regular
> >     // 'implementation' dep instead:
> >     //implementation 'com.google.android.mobly:mobly-snippet-lib:1.3.2'
> > ```
> 
> see above
> 
> _Code quote:_
> 
> ```groovy-gradle
> 1.3.2
> ```
> 
> _[`third_party/sl4a/gradle.properties` line 3 at r1](https://reviewable.io/reviews/google/mobly-snippet-lib/125#-NV1Fq_gBXceUfb8WiS8:-NVWXy4w7NJll1wx1hSn:b-8jhx0c) ([raw file](https://github.com/google/mobly-snippet-lib/blob/eda1ecc0e53162d679097ac61467a6854ffdbe7b/third_party/sl4a/gradle.properties#L3)):_
> 
> Previously, ko1in1u (Kolin Lu) wrote…
> change to 1040099?

Updated, thank you.

**Comment by ko1in1u** [comment]
Accidentally closed

**Review by xianyuanjia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly-snippet-lib/125)* status: 0 of 14 files reviewed, 4 unresolved discussions (waiting on @ko1in1u and @xpconanfan)

*[a discussion](https://reviewable.io/reviews/google/mobly-snippet-lib/125#-NVWhtJV-Ze8jV-WQoGa:-NVWhtJV-Ze8jV-WQoGb:b-azkut8) (no related file):*
Could the TODO cleanup part be split into its own PR?

___

**Review by xianyuanjia — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/google/mobly-snippet-lib/125)* status: 0 of 14 files reviewed, 7 unresolved discussions (waiting on @ko1in1u and @xpconanfan)

___
*[`CHANGELOG` line 5 at r4](https://reviewable.io/reviews/google/mobly-snippet-lib/125#-NVWiHNK2CWTL0tCmYSV:-NVWhKdP0Q1N7UyIjOey:bvopeej) ([raw file](https://github.com/google/mobly-snippet-lib/blob/ba888ec5a7cbc4dade8b3cbf01ad36480fb241fe/CHANGELOG#L5)):*
> ```
>   - Support primitive array types in JsonBuilder 
>   - Setting class loader before unmarshalling bundle to prevent java.lang.ClassNotFoundException.
>   - Use Maven Central for snippet-lib releases; clean up Gradle configs 
> ```

Gradle changes don't have to be in the changelog. 
___
*[`CHANGELOG` line 6 at r4](https://reviewable.io/reviews/google/mobly-snippet-lib/125#-NVWiMZmB8pFfkC-HqR2:-NVWiMZmB8pFfkC-HqR3:b4dwki) ([raw file](https://github.com/google/mobly-snippet-lib/blob/ba888ec5a7cbc4dade8b3cbf01ad36480fb241fe/CHANGELOG#L6)):*
> ```
>   - Setting class loader before unmarshalling bundle to prevent java.lang.ClassNotFoundException.
>   - Use Maven Central for snippet-lib releases; clean up Gradle configs 
>   - Added Notification for O
> ```

This refers to https://github.com/google/mobly-snippet-lib/pull/93 right? It was already added in 1.3.1.
___
*[`CHANGELOG` line 7 at r4](https://reviewable.io/reviews/google/mobly-snippet-lib/125#-NVWiIj7ENAMFXwuIOsz:-NVWiIj7ENAMFXwuIOt-:b-7ioxry) ([raw file](https://github.com/google/mobly-snippet-lib/blob/ba888ec5a7cbc4dade8b3cbf01ad36480fb241fe/CHANGELOG#L7)):*
> ```
>   - Use Maven Central for snippet-lib releases; clean up Gradle configs 
>   - Added Notification for O
>   - Update Gradle, project dependencies, and SDK versions
> ```

Ditto above

**Comment by ko1in1u** [comment]
Branch is a little bit messed up, will create 126 and 127 to fix.

**Pull request closed without merging**
