### PR TITLE
Create an example for how to use UIAutomator.

### LINKED ISSUE #33: Snippets are not compatible with UIAutomator
'am instrument' only sets up a UiAutomationConnection in -w mode. I don't know why, but snippets are not run in wait mode, so UiAutomationConnection is null. This crashes uiautomator, which needs that proxy object for privileged operations back to the shell.

### PR DESCRIPTION
**Pull request by adorokhine**
Actually getting this to work requires client-side changes which are
tracked in https://github.com/google/mobly/issues/166.

Fixes #33.

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-snippet-lib/54)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Reviewed 2 of 18 files at r1.
Review status: 2 of 18 files reviewed at latest revision, 7 unresolved discussions.

---

*[examples/ex4_uiautomator/README.md, line 9 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-Kg0oxJo1p3IkXstEmSO:-Kg0oxJo1p3IkXstEmSP:bsshwr4) ([raw file](https://github.com/google/mobly-snippet-lib/blob/fdadcfa7e74f0dcb3cb3b4f0471f46bc20aaa3a7/examples/ex4_uiautomator/README.md#L9)):*
> ```Markdown
> 1.  Set up your build rules following the examples in the
>     [Espresso snippet tutorial](../ex2_espresso/README.md).
> ```

Could we briefly describe what a user is expected to see after launching the app?

---

*[examples/ex4_uiautomator/src/main/java/com/google/android/mobly/snippet/example4/MainActivity.java, line 2 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-Kg0p66DymhavZMQLv7V:-Kg0p66DymhavZMQLv7W:bj7uc6s) ([raw file](https://github.com/google/mobly-snippet-lib/blob/fdadcfa7e74f0dcb3cb3b4f0471f46bc20aaa3a7/examples/ex4_uiautomator/src/main/java/com/google/android/mobly/snippet/example4/MainActivity.java#L2)):*
> ```Java
> /*
>  * Copyright (C) 2016 Google Inc.
> ```

2017
other files too.

---

*[examples/ex4_uiautomator/src/main/java/com/google/android/mobly/snippet/example4/MainActivity.java, line 25 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-Kg0pH0tG0Wexf9Rkred:-Kg0pH0uSy91uzdzoI-R:b-6x3bs0) ([raw file](https://github.com/google/mobly-snippet-lib/blob/fdadcfa7e74f0dcb3cb3b4f0471f46bc20aaa3a7/examples/ex4_uiautomator/src/main/java/com/google/android/mobly/snippet/example4/MainActivity.java#L25)):*
> ```Java
> import android.widget.TextView;
> 
> public class MainActivity extends AppCompatActivity {
> ```

I assume this is the actual app under test?
Could we add javadoc describing what this app is expected to have?

---

*[examples/ex4_uiautomator/src/main/res/mipmap-hdpi/ic_launcher.png, line 0 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-Kg-w8dkyfPCMan7eV3L:-Kg-w8dkyfPCMan7eV3M:b9mgtv0) ([raw file](https://github.com/google/mobly-snippet-lib/blob/fdadcfa7e74f0dcb3cb3b4f0471f46bc20aaa3a7/examples/ex4_uiautomator/src/main/res/mipmap-hdpi/ic_launcher.png#L0)):*
Do we have license for these pngs?

---

*[examples/ex4_uiautomator/src/snippet/java/com/google/android/mobly/snippet/example4/UiAutomatorSnippet.java, line 35 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-Kg0pVQMvhZlpJigPhPS:-Kg0pVQMvhZlpJigPhPT:by85hp5) ([raw file](https://github.com/google/mobly-snippet-lib/blob/fdadcfa7e74f0dcb3cb3b4f0471f46bc20aaa3a7/examples/ex4_uiautomator/src/snippet/java/com/google/android/mobly/snippet/example4/UiAutomatorSnippet.java#L35)):*
> ```Java
> import java.nio.charset.Charset;
> 
> @SdkSuppress(minSdkVersion = 18)
> ```

In gradle file, we used minSdk 11.
Should that be 18 if this is 18?

---

*[examples/ex4_uiautomator/src/snippet/java/com/google/android/mobly/snippet/example4/UiAutomatorSnippet.java, line 70 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-Kg0q-q079D_Gcyv_g3e:-Kg0q-q079D_Gcyv_g3f:b-cwkhcp) ([raw file](https://github.com/google/mobly-snippet-lib/blob/fdadcfa7e74f0dcb3cb3b4f0471f46bc20aaa3a7/examples/ex4_uiautomator/src/snippet/java/com/google/android/mobly/snippet/example4/UiAutomatorSnippet.java#L70)):*
> ```Java
> 
>     @Rpc(description="Clicks the button")
>     public void click() {
> ```

We should probably not encourage ppl to use generic names like this.
How about we give each button a name and name the methods accordingly?

---

*[examples/ex4_uiautomator/src/snippet/java/com/google/android/mobly/snippet/example4/UiAutomatorSnippet.java, line 89 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-Kg0pu-cYVS2zTEEA6Hj:-Kg0pu-cYVS2zTEEA6Hk:b-edokis) ([raw file](https://github.com/google/mobly-snippet-lib/blob/fdadcfa7e74f0dcb3cb3b4f0471f46bc20aaa3a7/examples/ex4_uiautomator/src/snippet/java/com/google/android/mobly/snippet/example4/UiAutomatorSnippet.java#L89)):*
> ```Java
> 
>     @Override
>     public void shutdown() {}
> ```

is there any step to be performed here, like stopping the main activity if it's launched?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54)*

**Comment by adorokhine** [comment]
Review status: 0 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[examples/ex4_uiautomator/README.md, line 9 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-Kg0oxJo1p3IkXstEmSO:-KjeznLCZogLD5IxaKBD:bukihmj) ([raw file](https://github.com/google/mobly-snippet-lib/blob/fdadcfa7e74f0dcb3cb3b4f0471f46bc20aaa3a7/examples/ex4_uiautomator/README.md#L9)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Could we briefly describe what a user is expected to see after launching the app?
</blockquote></details>

I thought your concern with documenting things that the user could try and see for themselves was that we would have to maintain the documentation? That was the reason you gave for not wanting to document the serialized versions of our data structures.

---

*[examples/ex4_uiautomator/src/main/java/com/google/android/mobly/snippet/example4/UiAutomatorSnippet.java, line 89 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-Kg0pu-cYVS2zTEEA6Hj:-KjfLQIzi7eIYQ_p3LQd:b9p6xf6) ([raw file](https://github.com/google/mobly-snippet-lib/blob/fdadcfa7e74f0dcb3cb3b4f0471f46bc20aaa3a7/examples/ex4_uiautomator/src/main/java/com/google/android/mobly/snippet/example4/UiAutomatorSnippet.java#L89)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

is there any step to be performed here, like stopping the main activity if it's launched?
</blockquote></details>

Optional but done.

---

*[examples/ex4_uiautomator/src/main/java/com/google/android/mobly/snippet/example4/MainActivity.java, line 2 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-Kg0p66DymhavZMQLv7V:-KjfL5foCdbk3dGlc8E3:b-ruqkw2) ([raw file](https://github.com/google/mobly-snippet-lib/blob/fdadcfa7e74f0dcb3cb3b4f0471f46bc20aaa3a7/examples/ex4_uiautomator/src/main/java/com/google/android/mobly/snippet/example4/MainActivity.java#L2)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

2017
other files too.
</blockquote></details>

Obsolete

---

*[examples/ex4_uiautomator/src/main/java/com/google/android/mobly/snippet/example4/MainActivity.java, line 25 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-Kg0pH0tG0Wexf9Rkred:-Kjf-ekJqBCGLe0-jr-k:bklnu7c) ([raw file](https://github.com/google/mobly-snippet-lib/blob/fdadcfa7e74f0dcb3cb3b4f0471f46bc20aaa3a7/examples/ex4_uiautomator/src/main/java/com/google/android/mobly/snippet/example4/MainActivity.java#L25)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

I assume this is the actual app under test?
Could we add javadoc describing what this app is expected to have?
</blockquote></details>

See my other comment; I thought we didn't want to maintain this kind of doc?

---

*[examples/ex4_uiautomator/src/main/res/mipmap-hdpi/ic_launcher.png, line  at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-Kg-w8dkyfPCMan7eV3L:-Kjf3MaCnR5QDfD85Oj9:b-ucnips) ([raw file](https://github.com/google/mobly-snippet-lib/blob/fdadcfa7e74f0dcb3cb3b4f0471f46bc20aaa3a7/examples/ex4_uiautomator/src/main/res/mipmap-hdpi/ic_launcher.png#L)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Do we have license for these pngs?
</blockquote></details>

Yes, it's Apache:
https://android.googlesource.com/platform/tools/base/+/master/templates/NOTICE

---

*[examples/ex4_uiautomator/src/snippet/java/com/google/android/mobly/snippet/example4/UiAutomatorSnippet.java, line 35 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-Kg0pVQMvhZlpJigPhPS:-Kjf3_qi6vQrEtWGF6Bb:b-ruqkw2) ([raw file](https://github.com/google/mobly-snippet-lib/blob/fdadcfa7e74f0dcb3cb3b4f0471f46bc20aaa3a7/examples/ex4_uiautomator/src/snippet/java/com/google/android/mobly/snippet/example4/UiAutomatorSnippet.java#L35)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

In gradle file, we used minSdk 11.
Should that be 18 if this is 18?
</blockquote></details>

Obsolete

---

*[examples/ex4_uiautomator/src/snippet/java/com/google/android/mobly/snippet/example4/UiAutomatorSnippet.java, line 70 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-Kg0q-q079D_Gcyv_g3e:-Kjf4eYghWTk_CCNtxh2:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/fdadcfa7e74f0dcb3cb3b4f0471f46bc20aaa3a7/examples/ex4_uiautomator/src/snippet/java/com/google/android/mobly/snippet/example4/UiAutomatorSnippet.java#L70)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

We should probably not encourage ppl to use generic names like this.
How about we give each button a name and name the methods accordingly?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54)*

**Comment by dthkao** [comment]
Review status: 0 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[examples/ex4_uiautomator/src/main/AndroidManifest.xml, line 14 at r2](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-Kjh8ykYokHh7ZfcAfnP:-Kjh8ykZZCjK3xvlnLp3:bilsap8) ([raw file](https://github.com/google/mobly-snippet-lib/blob/f9851005621a0f7fe277b602dd5ff925c0128282/examples/ex4_uiautomator/src/main/AndroidManifest.xml#L14)):*
> ```XML
>     <instrumentation
>         android:name="com.google.android.mobly.snippet.SnippetRunner"
>         android:targetPackage="com.google.android.mobly.snippet.example4" />
> ```

Can we highlight in the README that this does not need to target any package we may swipe/click through?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54)*

**Comment by xpconanfan** [comment]
Review status: 0 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[examples/ex4_uiautomator/README.md, line 17 at r2](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-KjiXYtPfU-YDgFMbc_1:-KjiXYtPfU-YDgFMbc_2:b-kf18jr) ([raw file](https://github.com/google/mobly-snippet-lib/blob/f9851005621a0f7fe277b602dd5ff925c0128282/examples/ex4_uiautomator/README.md#L17)):*
> ```Markdown
> 1.  Compile the main app and automation
> 
>         ./gradlew examples:ex2_espresso:assembleDebug examples:ex4_uiautomator:assembleDebug
> ```

Hmm, I'm confused.
We need to build both ex2 and ex4 in the README for ex4?
This seems more complicated than the previous patch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54)*

**Comment by adorokhine** [comment]
Review status: 0 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[examples/ex4_uiautomator/README.md, line 17 at r2](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-KjiXYtPfU-YDgFMbc_1:-KjikoBPFkR218DL_lT_:bmtq2qz) ([raw file](https://github.com/google/mobly-snippet-lib/blob/f9851005621a0f7fe277b602dd5ff925c0128282/examples/ex4_uiautomator/README.md#L17)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Hmm, I'm confused.
We need to build both ex2 and ex4 in the README for ex4?
This seems more complicated than the previous patch.
</blockquote></details>

The example is now showing how to instrument an app you don't have source access to.
If you're automating Google Maps you'll have to build and install both your snippet and Maps. That's what this is doing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54)*

**Comment by xpconanfan** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/ex4_uiautomator/README.md, line 17 at r2](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-KjiXYtPfU-YDgFMbc_1:-KjimaU3vL2Eu2L5OwbD:b-lb97kj) ([raw file](https://github.com/google/mobly-snippet-lib/blob/f9851005621a0f7fe277b602dd5ff925c0128282/examples/ex4_uiautomator/README.md#L17)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

The example is now showing how to instrument an app you don't have source access to.
If you're automating Google Maps you'll have to build and install both your snippet and Maps. That's what this is doing.
</blockquote></details>

Got it.

Could we clarify the intention?
We are using ex2 as the target here and pretend we don't have source access to it even though the reader can indeed access its source, that's what confused me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54)*

**Comment by adorokhine** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/ex4_uiautomator/README.md, line 17 at r2](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-KjiXYtPfU-YDgFMbc_1:-KkrvgpTLEs6hoVy5fYM:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/f9851005621a0f7fe277b602dd5ff925c0128282/examples/ex4_uiautomator/README.md#L17)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Got it.

Could we clarify the intention?
We are using ex2 as the target here and pretend we don't have source access to it even though the reader can indeed access its source, that's what confused me.
</blockquote></details>

Done.

---

*[examples/ex4_uiautomator/src/main/AndroidManifest.xml, line 14 at r2](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-Kjh8ykYokHh7ZfcAfnP:-KkrwF90J9Cr3KZllP3i:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/f9851005621a0f7fe277b602dd5ff925c0128282/examples/ex4_uiautomator/src/main/AndroidManifest.xml#L14)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Can we highlight in the README that this does not need to target any package we may swipe/click through?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/54#-:-KkskrH2eQU0RBnPOX-Q:bnfp4nl)*

**Pull request merged**
