### PR TITLE
walk stack instead of hard-coded depth

### LINKED ISSUE #69: ArrayIndexOutOfBoundsException with Proguard
The exception will be thrown inside Log.getTag(). Message is:

java.lang.ArrayIndexOutOfBoundsException: length=4; index=4.

This was caused by a hard-coded stack depth (4) inside Log.getTag() function. Proguard will do inline optimization hence the call stack is different (shallower) with proguard.

Instead of use a hard-coded value, a better way is to walk up the stack until we see a class name that's neither us nor android.util.Log: that's the real caller.

### PR DESCRIPTION
**Pull request by jhshi**
Attempt to fix #69

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-snippet-lib/70)

### CODE REVIEW

**Comment by jhshi** [comment]
Signed the CLA.

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[third_party/sl4a/src/main/java/com/google/android/mobly/snippet/util/Log.java, line 66 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/70#-KrgPzusZb9-0KADIVNd:-KrgPzusZb9-0KADIVNe:b-va0ql9) ([raw file](https://github.com/google/mobly-snippet-lib/blob/263beab52a0f74ce38a3479aca178717428afbcf/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/util/Log.java#L66)):*
> ```Java
>         // inline optimization.
>         for (StackTraceElement element : stackTraceElements) {
>           fullClassName = element.getClassName();
> ```

if we walk through the whole stack and we don't find a class name that satisfies the condition, we'd end up with whatever the last `fullClassName` is, which seems incorrect.

Maybe we should use a default name in this case.

---

*[third_party/sl4a/src/main/java/com/google/android/mobly/snippet/util/Log.java, line 67 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/70#-KrgQGjz22y9ylfSZROE:-KrgQGjz22y9ylfSZROF:bl02txx) ([raw file](https://github.com/google/mobly-snippet-lib/blob/263beab52a0f74ce38a3479aca178717428afbcf/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/util/Log.java#L67)):*
> ```Java
>         for (StackTraceElement element : stackTraceElements) {
>           fullClassName = element.getClassName();
>           if (!fullClassName.equals(Log.class.getName()) &&
> ```

Perhaps we could make local vars for these names so we only need to call `getName` on them once.
That'll also give us a chance to explain in comment why these two names are used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/70)*

**Comment by jhshi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[third_party/sl4a/src/main/java/com/google/android/mobly/snippet/util/Log.java, line 66 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/70#-KrgPzusZb9-0KADIVNd:-KrqXE4zW81emxYhGS5l:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/263beab52a0f74ce38a3479aca178717428afbcf/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/util/Log.java#L66)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

if we walk through the whole stack and we don't find a class name that satisfies the condition, we'd end up with whatever the last `fullClassName` is, which seems incorrect.

Maybe we should use a default name in this case.
</blockquote></details>

Done.

---

*[third_party/sl4a/src/main/java/com/google/android/mobly/snippet/util/Log.java, line 67 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/70#-KrgQGjz22y9ylfSZROE:-KrqXFAxhG-6_1WnDx56:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/263beab52a0f74ce38a3479aca178717428afbcf/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/util/Log.java#L67)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Perhaps we could make local vars for these names so we only need to call `getName` on them once.
That'll also give us a chance to explain in comment why these two names are used.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/70)*

**Comment by xpconanfan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/70)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/70#-:-KrqiBkfckxnnal8hO_D:bnfp4nl)*

**Pull request merged**
