### PR TITLE
Update gradle, dependency versions and fix lint reported issues

### PR DESCRIPTION
**Pull request by kdart**
Update the lib to compile and lint with latest SDK and other library versions. Add presubmit target like bundled snippets has. 

♃ src/mobly-snippet-lib|buildupdates ⇒ ./gradlew lint

> Task :mobly-snippet-lib:lint
Ran lint on variant release: 0 issues found
Ran lint on variant debug: 0 issues found

> Task :examples:ex1_standalone_app:lint
Ran lint on variant debug: 0 issues found
Ran lint on variant release: 0 issues found

> Task :examples:ex2_espresso:lint
Ran lint on variant mainDebug: 0 issues found
Ran lint on variant snippetDebug: 0 issues found
Ran lint on variant snippetRelease: 0 issues found
Ran lint on variant mainRelease: 0 issues found

> Task :examples:ex3_async_event:lint
Ran lint on variant debug: 0 issues found
Ran lint on variant release: 0 issues found

> Task :examples:ex4_uiautomator:lint
Ran lint on variant debug: 0 issues found
Ran lint on variant release: 0 issues found

> Task :examples:ex5_schedule_rpc:lint
Ran lint on variant debug: 0 issues found
Ran lint on variant release: 0 issues found

BUILD SUCCESSFUL in 26s
337 actionable tasks: 27 executed, 310 up-to-date

... and ... 
♃ src/mobly-snippet-lib|buildupdates ⇒ ./gradlew presubmit

> Task :mobly-snippet-lib:lint
Ran lint on variant release: 0 issues found
Ran lint on variant debug: 0 issues found

> Task :mobly-snippet-lib:presubmit
Fix any lint issues you see. When it looks good, submit the pull request.

BUILD SUCCESSFUL in 4s
25 actionable tasks: 3 executed, 22 up-to-date

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-snippet-lib/80)

### CODE REVIEW

**Comment by kdart** [comment]
Review status: 0 of 22 files reviewed at latest revision, 12 unresolved discussions.

---

*[build.gradle, line 10 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80#-KxnIAYnq8q3RN5X41z9:-Kxn_WQrpulm_E8rtC9b:b-3r1zlp) ([raw file](https://github.com/google/mobly-snippet-lib/blob/2573fe9c2e2b130edad59a45c3fa7bf1552222b7/build.gradle#L10)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

intended for removal? or why the pre-release version below?
</blockquote></details>

Yes, was just testing it, and it works. So it can be removed. the pre-release was latest at the time. Now it's released. :-)

---

*[build.gradle, line 10 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80#-KxnI5FhSWmwjrsB81v6:-KxnaDDLkCFkeWIdwqJ6:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/f48f37f7a4de86306cc7193d92b464fab491b67b/build.gradle#L10)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

please don't remove this
</blockquote></details>

Done.

---

*[build.gradle, line 26 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80#-KxnIoqd3n6WAYfDR23P:-KxnaPD0kLoNnd_r8MtV:b-7tvtmx) ([raw file](https://github.com/google/mobly-snippet-lib/blob/f48f37f7a4de86306cc7193d92b464fab491b67b/build.gradle#L26)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

why remove?
</blockquote></details>

Removals such as this are due to gradle and/or lint and/or studio complaining about something. Apparently, this is now redundant. 

---

*[examples/ex1_standalone_app/build.gradle, line 15 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80#-KxnIsmFwlNAdVJUITEc:-KxnahQkbwcqROqY0B5-:b-ub03l9) ([raw file](https://github.com/google/mobly-snippet-lib/blob/f48f37f7a4de86306cc7193d92b464fab491b67b/examples/ex1_standalone_app/build.gradle#L15)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

please leave this as true
</blockquote></details>

It works more nicely with the presubmit target. Have you tried it?
 

---

*[examples/ex1_standalone_app/build.gradle, line 26 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80#-KxnJEJL1Q4IpXGCo48H:-KxnbJwqQJ-NxBmcLsiH:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/2573fe9c2e2b130edad59a45c3fa7bf1552222b7/examples/ex1_standalone_app/build.gradle#L26)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

whatever we do with the gradle version above let's make this consistent
</blockquote></details>

Done.

---

*[examples/ex2_espresso/build.gradle, line 26 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80#-KxnJUjJyT4O01dGA4Fk:-KxnbgAesG_-Uy4RVAbM:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/2573fe9c2e2b130edad59a45c3fa7bf1552222b7/examples/ex2_espresso/build.gradle#L26)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

revert
</blockquote></details>

Done.

---

*[examples/ex2_espresso/src/main/res/layout/activity_main.xml, line 11 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80#-KxnJinRMhmF5Wq2dzf1:-KxnbjMdRVq09pS-Mvjw:b-79gll7) ([raw file](https://github.com/google/mobly-snippet-lib/blob/f48f37f7a4de86306cc7193d92b464fab491b67b/examples/ex2_espresso/src/main/res/layout/activity_main.xml#L11)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Any reason for removing the outer UI layer?
</blockquote></details>

IDE suggested it, claims it didn't effect the UI at all. 

---

*[third_party/sl4a/build.gradle, line 26 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80#-KxnK3DwIQ77zt4vMsqg:-KxnbyJ_VTtfwxJKHWNN:bax0ed7) ([raw file](https://github.com/google/mobly-snippet-lib/blob/2573fe9c2e2b130edad59a45c3fa7bf1552222b7/third_party/sl4a/build.gradle#L26)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

@Ang, is this ok?
</blockquote></details>

This is what we set MBS to, since IDE/lint claims 15  covers  all currently supported devices. 

---

*[third_party/sl4a/build.gradle, line 36 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80#-KxnK8qux6ADOEHSpeRi:-KxncOUAGpznlw6lxxNn:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/2573fe9c2e2b130edad59a45c3fa7bf1552222b7/third_party/sl4a/build.gradle#L36)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

if not usable, let's remove
</blockquote></details>

Done.

---

*[third_party/sl4a/build.gradle, line 52 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80#-KxnKDSsVP9X665Cdd8k:-KxncWyoUHBCxhNnOiCI:b8oh5vb) ([raw file](https://github.com/google/mobly-snippet-lib/blob/2573fe9c2e2b130edad59a45c3fa7bf1552222b7/third_party/sl4a/build.gradle#L52)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

true
</blockquote></details>

This is helpful for getting a full HTML report from lint, up front. If you're not using the IDE it's very helpful. 

---

*[third_party/sl4a/src/main/java/com/google/android/mobly/snippet/event/EventCache.java, line 22 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80#-KxnKJf3I8WZjRu5SSN1:-Kxncj4G8NELanExdDHz:b-g6jfqp) ([raw file](https://github.com/google/mobly-snippet-lib/blob/2573fe9c2e2b130edad59a45c3fa7bf1552222b7/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/event/EventCache.java#L22)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Was localization causing lint errors?
</blockquote></details>

Yes, lint warned that this is a potential source of bugs. We did the same thing with MBS. 

---

*[third_party/sl4a/src/main/java/com/google/android/mobly/snippet/rpc/SimpleServer.java, line 165 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80#-KxnLNWhxcYOPNmwCVeY:-Kxndj9zCfLt8GWG_965:btr5wqo) ([raw file](https://github.com/google/mobly-snippet-lib/blob/f48f37f7a4de86306cc7193d92b464fab491b67b/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/rpc/SimpleServer.java#L165)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

If we'll never use this again, perhaps change the other method to just getInetAddress (also we should probably have some sort of docstring)
</blockquote></details>

It might be confused with the Socket getInetAddress method. This isn't even used anywhere else so it could probably be made private. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80)*

**Comment by dthkao** [comment]
Review status: 0 of 22 files reviewed at latest revision, 8 unresolved discussions.

---

*[examples/ex1_standalone_app/build.gradle, line 15 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80#-KxnIsmFwlNAdVJUITEc:-Kxt5kNHQd6DtPysvzsk:byqg4qq) ([raw file](https://github.com/google/mobly-snippet-lib/blob/f48f37f7a4de86306cc7193d92b464fab491b67b/examples/ex1_standalone_app/build.gradle#L15)):*
<details><summary><i>Previously, kdart (Keith Dart) wrote…</i></summary><blockquote>

It works more nicely with the presubmit target. Have you tried it?
 
</blockquote></details>

But this means that build will not fail on lint error (which was the original intent of adding it). Do you know if there is a way to fail build but still get the proper lint reports in presubmit?

---

*[third_party/sl4a/build.gradle, line 26 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80#-KxnK3DwIQ77zt4vMsqg:-Kxt67sGNQB-qwFA-pNQ:b-1dhxc6) ([raw file](https://github.com/google/mobly-snippet-lib/blob/2573fe9c2e2b130edad59a45c3fa7bf1552222b7/third_party/sl4a/build.gradle#L26)):*
<details><summary><i>Previously, kdart (Keith Dart) wrote…</i></summary><blockquote>

This is what we set MBS to, since IDE/lint claims 15  covers  all currently supported devices. 
</blockquote></details>

the bundle and the lib can have different requirements, but I checked with Ang and as far as we know the lowest sdk anyone uses the lib for is still ok.

---

*[third_party/sl4a/src/main/java/com/google/android/mobly/snippet/rpc/SimpleServer.java, line 165 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80#-KxnLNWhxcYOPNmwCVeY:-Kxt6Ttdhhp2lLTMXr8T:b2lzmdv) ([raw file](https://github.com/google/mobly-snippet-lib/blob/f48f37f7a4de86306cc7193d92b464fab491b67b/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/rpc/SimpleServer.java#L165)):*
<details><summary><i>Previously, kdart (Keith Dart) wrote…</i></summary><blockquote>

It might be confused with the Socket getInetAddress method. This isn't even used anywhere else so it could probably be made private. 
</blockquote></details>

+1 to making it private

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80)*

**Comment by kdart** [comment]
Review status: 0 of 22 files reviewed at latest revision, 8 unresolved discussions.

---

*[examples/ex1_standalone_app/build.gradle, line 15 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80#-KxnIsmFwlNAdVJUITEc:-KxtEWl8AszvZGnXR6uN:b-agbet7) ([raw file](https://github.com/google/mobly-snippet-lib/blob/f48f37f7a4de86306cc7193d92b464fab491b67b/examples/ex1_standalone_app/build.gradle#L15)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

But this means that build will not fail on lint error (which was the original intent of adding it). Do you know if there is a way to fail build but still get the proper lint reports in presubmit?
</blockquote></details>

I don't think there is. But I found this way to be a little more productive. Instead of fixing lint errors one at a time, you can get a full report and fix more at once, and the HTML report has some nice suggestions as well. You just have to remember to do it this way, and that it won't fail. It seems that lint wasn't even being  used much previously, anyway. Besides, what does it mean to get a "build error", when you are not building? It's just a static check and it's more helpful to get the most out of it up front. 

For MBS we documented the usage of the presubmit target there. So you shouldn't really be running lint target in this setup. 

---

*[third_party/sl4a/src/main/java/com/google/android/mobly/snippet/rpc/SimpleServer.java, line 165 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80#-KxnLNWhxcYOPNmwCVeY:-KxtJ7L-WbDkp7ChF3iH:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/f48f37f7a4de86306cc7193d92b464fab491b67b/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/rpc/SimpleServer.java#L165)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

+1 to making it private
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80)*

**Comment by dthkao** [comment]
:lgtm:

---

Review status: 0 of 22 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/80#-:-KyWp10Ct9XlWYgItUsh:bnfp4nl)*

**Pull request merged**
