### PR TITLE
Add a dedicated example for async rpc.

### LINKED ISSUE #40: Create doc for async rpc
In addition to the basic usage, we should also give sample use cases based on our experience with async events.

### LINKED ISSUE #42: help() crashes when there's @AsyncRpc defined
If there are methods using `@AsyncRpc` defined in the snippet, the help() call would crash snippet.

### PR DESCRIPTION
**Pull request by xpconanfan**
Also fix a bug where help() fails if AsyncRpc exists.
fixes #40 
fixes #42

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-snippet-lib/43)

### CODE REVIEW

**Comment by adorokhine** [comment]
Reviewed 4 of 7 files at r1.
Review status: 4 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 2 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-Kddag-WH2GYcJMnDjhP:-Kddag-Xliw39OeSYRUz:b-8k88p6) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L2)):*
> ```Java
> /*
>  * Copyright (C) 2016 Google Inc.
> ```

2017?

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 29 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KddajSkFFtfKPklwp3v:-KddajSkFFtfKPklwp3w:bhzot2y) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L29)):*
> ```Java
> public class ExampleAsyncSnippet implements Snippet {
> 
>     private final EventCache mEventQueue = EventCache.getInstance();
> ```

Object called cache, but variable called queue. Could we use a consistent term?

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 39 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KddarzHfjMXGB1T50ev:-KddarzHfjMXGB1T50ew:b3g8oko) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L39)):*
> ```Java
>     public class AsyncTask implements Runnable {
> 
>         private String callbackId;
> ```

mCallbackId

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 52 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KddavrAfF9N9zq9QjcO:-KddavrAfF9N9zq9QjcP:b7nowhj) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L52)):*
> ```Java
>         public void run() {
>             try {
>                 Thread.sleep(10000);
> ```

Let's add a log here saying we're about to sleep to simulate a long-running task (in case someone is watching logcat) and maybe a line afterward saying processing is complete and an event is being sent (assuming none is printed by eventcache)

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 61 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KddbEKIMOh4q4hHQAZS:-KddbEKJNR_JBgnF1kbE:b-9cbbkc) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L61)):*
> ```Java
>                 event.addData("moreData", moreData);
>                 mEventQueue.postEvent(event);
>             } catch (Exception e) {
> ```

What can fail here?

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 76 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KddbK6mDTvntEKF0L0J:-KddbK6mDTvntEKF0L0K:b-ufjiyv) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L76)):*
> ```Java
>      *
>      * {
>      * 	'callbackId': <callbackID>,
> ```

Tabs being used in this comment instead of spaces; github renders them weird

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43)*

**Comment by adorokhine** [comment]
Reviewed 3 of 7 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[examples/ex3_async_event/README.md, line 27 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-Kddbs5kDDtzPd6g0w7I:-Kddbs5lXyg3Qu-7c7f6:bpf4p9k) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/README.md#L27)):*
> ```Markdown
>         >>> print("Not blocked, can do stuff here")
>         >>> eventHandler.waitAndGet('ExampleEvent') // Blocks until the event is posted on the server side
>         {'callbackId': '2-1', 'name': 'ExampleEvent', 'time': 20381008148, 'data': {'exampleData': "Here's a simple event.", 'secretNumber': 42, 'isSecretive': True, 'moreData': {'evenMoreData': 'More Data!'}}}
> ```

Maybe we can use pprint.pprint() here instead of a regular log so it's a little easier to read?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43)*

**Comment by xpconanfan** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[examples/ex3_async_event/README.md, line 27 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-Kddbs5kDDtzPd6g0w7I:-KddkTFd3P5t5Awyc91y:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/README.md#L27)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Maybe we can use pprint.pprint() here instead of a regular log so it's a little easier to read?
</blockquote></details>

Done.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 2 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-Kddag-WH2GYcJMnDjhP:-Kddl6P0r_lmlXImhmeU:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L2)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

2017?
</blockquote></details>

Done.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 29 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KddajSkFFtfKPklwp3v:-Kddl9qlwu-NftgL3_Sp:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L29)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Object called cache, but variable called queue. Could we use a consistent term?
</blockquote></details>

Done.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 39 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KddarzHfjMXGB1T50ev:-KddlFBApaJ7RpNbHGU4:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L39)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

mCallbackId
</blockquote></details>

Done.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 52 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KddavrAfF9N9zq9QjcO:-KddlIzi7OPCKv2TRk1R:bfibziw) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L52)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Let's add a log here saying we're about to sleep to simulate a long-running task (in case someone is watching logcat) and maybe a line afterward saying processing is complete and an event is being sent (assuming none is printed by eventcache)
</blockquote></details>

EventCache.postEvent logs.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 61 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KddbEKIMOh4q4hHQAZS:-KddlPA9AKp7PZ4nvnGW:b-d5b1r9) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L61)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

What can fail here?
</blockquote></details>

No idea, but runnable wouldn't let through any exception due to fixed signature.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 76 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KddbK6mDTvntEKF0L0J:-Kddltubmc2S_Ns566zp:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L76)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Tabs being used in this comment instead of spaces; github renders them weird
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43)*

**Comment by adorokhine** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 52 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KddavrAfF9N9zq9QjcO:-Kddw5cQZvAkiwBMEr7z:b-d6nsid) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L52)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

EventCache.postEvent logs.
</blockquote></details>

sg, just a log before the sleep then?

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 61 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KddbEKIMOh4q4hHQAZS:-KddwBD7DO93r_beisHH:b8sdv6a) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L61)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

No idea, but runnable wouldn't let through any exception due to fixed signature.
</blockquote></details>

We should be specific in what we wrap and catch.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 39 at r2](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-Kddw36-EJUnMuzbA_Cj:-Kddw36-EJUnMuzbA_Ck:b7hycdm) ([raw file](https://github.com/google/mobly-snippet-lib/blob/0f8e85739b20eb5d9599d00eb54d7a39c6bf7291/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L39)):*
> ```Java
>     public class AsyncTask implements Runnable {
> 
>         private String mCallbackId;
> ```

Everything that can be final should be

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 40 at r2](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-Kddw1dnkNo6CRqbJ8mm:-Kddw1doh5_4h1H5Mp6c:brti2ip) ([raw file](https://github.com/google/mobly-snippet-lib/blob/0f8e85739b20eb5d9599d00eb54d7a39c6bf7291/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L40)):*
> ```Java
> 
>         private String mCallbackId;
>         private int secretNumber;
> ```

mSecretNumber

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43)*

**Comment by xpconanfan** [comment]
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 52 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KddavrAfF9N9zq9QjcO:-Kde3KwK_ZxXtey9OZfk:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L52)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

sg, just a log before the sleep then?
</blockquote></details>

Done.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 61 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KddbEKIMOh4q4hHQAZS:-Kde3hFaqE7xDdte8DaA:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L61)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

We should be specific in what we wrap and catch.
</blockquote></details>

Done.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 39 at r2](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-Kddw36-EJUnMuzbA_Cj:-Kde3p-SUrxd5-XvwGPu:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/0f8e85739b20eb5d9599d00eb54d7a39c6bf7291/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L39)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Everything that can be final should be
</blockquote></details>

Done.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 40 at r2](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-Kddw1dnkNo6CRqbJ8mm:-Kde3mJ200hNCdcRXmTH:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/0f8e85739b20eb5d9599d00eb54d7a39c6bf7291/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L40)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

mSecretNumber
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43)*

**Comment by adorokhine** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 61 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KddbEKIMOh4q4hHQAZS:-KdhKEEFK6h6C8mnGmCf:bmxagij) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L61)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why are we wrapping so much code into the InterruptedException catch? mEventCache.postEvent() doesn't seem to throw it. Try blocks should be as tight as possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43)*

**Comment by adorokhine** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 66 at r3](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KdhKhVdruTp-KXQwfKN:-KdhKhVdruTp-KXQwfKO:b1d538f) ([raw file](https://github.com/google/mobly-snippet-lib/blob/9ac8d3310f04ea919709bce83600042d5d612c1d/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L66)):*
> ```Java
>                 Log.e("Thread sleep was interrupted: " + e);
>             } catch (JSONException e) {
>                 Log.e("Failed to create the event to post: " + e);
> ```

This raises an interesting problem... the code knows something failed but the client side will wait until timeout even though no event is forthcoming. Should we show people how to listen for failures here too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43)*

**Comment by xpconanfan** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 61 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KddbEKIMOh4q4hHQAZS:-KdhMO2Y0mOmY6w-npar:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L61)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Why are we wrapping so much code into the InterruptedException catch? mEventCache.postEvent() doesn't seem to throw it. Try blocks should be as tight as possible.
</blockquote></details>

Done.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 66 at r3](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KdhKhVdruTp-KXQwfKN:-KdhMOM9QbRXFsk0tyq6:b-2jd7c4) ([raw file](https://github.com/google/mobly-snippet-lib/blob/9ac8d3310f04ea919709bce83600042d5d612c1d/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L66)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

This raises an interesting problem... the code knows something failed but the client side will wait until timeout even though no event is forthcoming. Should we show people how to listen for failures here too?
</blockquote></details>

It all comes down to SnippetEvent.addData throws JSONException...
Maybe it's better to use Bundle underneath instead of JSON, it is more consistent with Android APIs and adding data doesn't throw checked exception?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43)*

**Comment by xpconanfan** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 61 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KddbEKIMOh4q4hHQAZS:-KdhPIduD81SAD7_6GMW:bfe6z3t) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L61)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Pending the other discussion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43)*

**Comment by adorokhine** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 66 at r3](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KdhKhVdruTp-KXQwfKN:-KdhQrm6BxCF-SpaNMcP:bue8own) ([raw file](https://github.com/google/mobly-snippet-lib/blob/9ac8d3310f04ea919709bce83600042d5d612c1d/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L66)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

It all comes down to SnippetEvent.addData throws JSONException...
Maybe it's better to use Bundle underneath instead of JSON, it is more consistent with Android APIs and adding data doesn't throw checked exception?
</blockquote></details>

That's not the only issue; Thread.sleep() throws too. This is a good simulation of reality where the long-running operations fail sometimes. Should show users how to detect and recover from that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43)*

**Comment by xpconanfan** [comment]
Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 61 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KddbEKIMOh4q4hHQAZS:-KdhWH8n03GqEh2ECcST:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/140ac5e389a144921a81f0cac142606c91ccba8c/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L61)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Pending the other discussion.
</blockquote></details>

Done.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 66 at r3](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KdhKhVdruTp-KXQwfKN:-KdhVCWCIQeOPjJtbCD7:bwddibg) ([raw file](https://github.com/google/mobly-snippet-lib/blob/9ac8d3310f04ea919709bce83600042d5d612c1d/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L66)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

That's not the only issue; Thread.sleep() throws too. This is a good simulation of reality where the long-running operations fail sometimes. Should show users how to detect and recover from that.
</blockquote></details>

Discussed offline, changed `SnippetEvent` implementation to use `Bundle` instead of `JSONObject`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43)*

**Comment by adorokhine** [comment]
Reviewed 1 of 2 files at r4.
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 55 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KdhXGwIU8NAlyBxhq1b:-KdhXGwJIdpGoYl3gKmy:b-30zn1j) ([raw file](https://github.com/google/mobly-snippet-lib/blob/24d64af10bab0c2ee1a0c92da22f040b782ee416/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L55)):*
> ```Java
>                 Thread.sleep(10000);
>             } catch (InterruptedException e) {
>                 SnippetEvent event = new SnippetEvent(mCallbackId, "FailedEvent");
> ```

Since the passing case is ExampleEvent, shold this be FailedExampleEvent? ExampleFailedEvent? Or maybe keep ExampleEvent but set a field saying it failed or something?

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 81 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KdhXXQ-kzFOCJ2acoBG:-KdhXXQ0mj4tkmkAhZZI:b-c28dlr) ([raw file](https://github.com/google/mobly-snippet-lib/blob/24d64af10bab0c2ee1a0c92da22f040b782ee416/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L81)):*
> ```Java
>      *    'data': {
>      *        'exampleData': "Here's a simple event.",
>      *        'mSecretNumber': 22,
> ```

Bad search and replace? (do you know about refactor->rename?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43)*

**Comment by xpconanfan** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 55 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KdhXGwIU8NAlyBxhq1b:-KdhZiplDNltKRhdcaUx:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/24d64af10bab0c2ee1a0c92da22f040b782ee416/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L55)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Since the passing case is ExampleEvent, shold this be FailedExampleEvent? ExampleFailedEvent? Or maybe keep ExampleEvent but set a field saying it failed or something?
</blockquote></details>

Done.

---

*[examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java, line 81 at r4](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KdhXXQ-kzFOCJ2acoBG:-KdhZ5XegokCxW114LgY:b-ysduuj) ([raw file](https://github.com/google/mobly-snippet-lib/blob/24d64af10bab0c2ee1a0c92da22f040b782ee416/examples/ex3_async_event/src/main/java/com/google/android/mobly/snippet/example3/ExampleAsyncSnippet.java#L81)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Bad search and replace? (do you know about refactor->rename?)
</blockquote></details>

this is what refactor->rename did, it changed both the putInt line and here...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43)*

**Comment by adorokhine** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/ex3_async_event/README.md, line 26 at r5](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KdhcVoCe-MC4w0aml5a:-KdhcVoDvMKqahEcfhej:bz2hao8) ([raw file](https://github.com/google/mobly-snippet-lib/blob/1dfb35a4d7924a4c7e73f3916e1137880a935acc/examples/ex3_async_event/README.md#L26)):*
> ```Markdown
>         >>> eventHandler = s.tryEvent(42)
>         >>> print("Not blocked, can do stuff here")
>         >>> event = eventHandler.waitAndGet('ExampleEvent') // Blocks until the event is posted on the server side
> ```

This name changed (and so did the contents)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43)*

**Comment by xpconanfan** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/ex3_async_event/README.md, line 26 at r5](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-KdhcVoCe-MC4w0aml5a:-Kdhea1FSiqVxPeE2Lwn:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/1dfb35a4d7924a4c7e73f3916e1137880a935acc/examples/ex3_async_event/README.md#L26)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

This name changed (and so did the contents)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43)*

**Comment by adorokhine** [comment]
:lgtm:

---

Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/43#-:-Kdhek8iQ9zPc7ViFwEg:bnfp4nl)*

**Pull request merged**
