### PR TITLE
Project toolchain updates.

### PR DESCRIPTION
**Pull request by xpconanfan**
* Update to 3.0.1
* Update dep versions to latest
* Remove unused config
* Fix IDE warnings.

@kdart

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-snippet-lib/84)

### CODE REVIEW

**Comment by dthkao** [comment]
Thanks for sorting out kdart's merge. Makes this one much easier to review

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/ex2_espresso/build.gradle, line 34 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/84#-L0Vgh_rfIkBT3JEkInx:-L0Vgh_rfIkBT3JEkIny:b-g88lh0) ([raw file](https://github.com/google/mobly-snippet-lib/blob/a14f8c884ddea4ea0608bc49a480f248808dbd66/examples/ex2_espresso/build.gradle#L34)):*
> ```Gradle
> 
> configurations.all {
>     resolutionStrategy.force 'com.android.support:support-annotations:27.0.2'
> ```

Is it necessary to force like this? Doesn't the default resolution use the newest?

---

*[third_party/sl4a/build.gradle, line 63 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/84#-L0VgzTsoSjdWCBjmPZv:-L0VgzTsoSjdWCBjmPZw:bt7g8f9) ([raw file](https://github.com/google/mobly-snippet-lib/blob/4d02684ade1a312b39591a94a92328dc0b65b883/third_party/sl4a/build.gradle#L63)):*
> ```Gradle
> dependencies {
>     // implementation fileTree(include: ['*.jar'], dir: 'libs')
>     // implementation 'com.android.support:appcompat-v7:26.1.0'
> ```

Any idea why we commented these out before?

---

*[third_party/sl4a/src/main/java/com/google/android/mobly/snippet/SnippetRunner.java, line 163 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/84#-L0VhTNDcbtjwW2v7FNQ:-L0VhTNDcbtjwW2v7FNR:bqcfcw3) ([raw file](https://github.com/google/mobly-snippet-lib/blob/a14f8c884ddea4ea0608bc49a480f248808dbd66/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/SnippetRunner.java#L163)):*
> ```Java
>                 .setWhen(System.currentTimeMillis())
>                 .setContentTitle("Snippet Service");
>         Notification mNotification = builder.getNotification();
> ```

since it's no longer a member the var name no longer needs the m prefix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/84#-:-L0VhvdOgJwtD64rXHqA:bek5luf)*

**Comment by kdart** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/84)*

**Comment by xpconanfan** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/ex2_espresso/build.gradle, line 34 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/84#-L0Vgh_rfIkBT3JEkInx:-L0ex4wOVo_7LVu1jNGZ:bi0k8wn) ([raw file](https://github.com/google/mobly-snippet-lib/blob/a14f8c884ddea4ea0608bc49a480f248808dbd66/examples/ex2_espresso/build.gradle#L34)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Is it necessary to force like this? Doesn't the default resolution use the newest?
</blockquote></details>

Without this it will resolve to conflict and unable to compile

---

*[third_party/sl4a/build.gradle, line 63 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/84#-L0VgzTsoSjdWCBjmPZv:-L0ex9DjXssPBEVTJEWV:b-fyr6mz) ([raw file](https://github.com/google/mobly-snippet-lib/blob/4d02684ade1a312b39591a94a92328dc0b65b883/third_party/sl4a/build.gradle#L63)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

Any idea why we commented these out before?
</blockquote></details>

No idea, these were carried from last PR.

---

*[third_party/sl4a/src/main/java/com/google/android/mobly/snippet/SnippetRunner.java, line 163 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/84#-L0VhTNDcbtjwW2v7FNQ:-L0f0dnplloDtMlStH5-:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/a14f8c884ddea4ea0608bc49a480f248808dbd66/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/SnippetRunner.java#L163)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

since it's no longer a member the var name no longer needs the m prefix.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/84)*

**Comment by dthkao** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/ex2_espresso/build.gradle, line 34 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/84#-L0Vgh_rfIkBT3JEkInx:-L0zltLeRtCYDpbdEMWC:b-99bjg8) ([raw file](https://github.com/google/mobly-snippet-lib/blob/a14f8c884ddea4ea0608bc49a480f248808dbd66/examples/ex2_espresso/build.gradle#L34)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Without this it will resolve to conflict and unable to compile
</blockquote></details>

That seems like a bug, or possibly a result of warningsAsErrors true above. From https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html

"In case of conflict, Gradle by default uses the newest of conflicting versions. However, you can change this behavior. Use this method [failOnVersionConflict()] to configure the resolution to fail eagerly on any version conflict, e.g. multiple different versions of the same dependency (group and name are equal) ...."

My concern is that line might result in a release of snippet lib forcing users library to an older version.

---

*[third_party/sl4a/build.gradle, line 63 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/84#-L0VgzTsoSjdWCBjmPZv:-L0zmbBhPQCKh5XA3HWe:bf0xbc7) ([raw file](https://github.com/google/mobly-snippet-lib/blob/4d02684ade1a312b39591a94a92328dc0b65b883/third_party/sl4a/build.gradle#L63)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

No idea, these were carried from last PR.
</blockquote></details>

But we're uncommenting one now. That seems worrisome.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/84)*

**Pull request closed without merging**
