### PR TITLE
Fix format warnings

### PR DESCRIPTION
**Pull request by l-meng**
Fix format warnings

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-snippet-lib/66)

### CODE REVIEW

**Comment by adorokhine** [comment]
:lgtm: Leaving final approval for David

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/66#-:-Kn5i9U1CeBvJVrg9xhM:b-kilcsb)*

**Comment by dthkao** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[examples/ex5_schedule_rpc/src/main/java/com/google/android/mobly/snippet/example5/ExampleScheduleRpcSnippet.java, line 31 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/66#-Kn5ie3rsz7gc7itMaFV:-Kn5ie3rsz7gc7itMaFW:bcdkb8) ([raw file](https://github.com/google/mobly-snippet-lib/blob/c6d4bfdc3d7accfe1945f3c6e15edff98a825fc9/examples/ex5_schedule_rpc/src/main/java/com/google/android/mobly/snippet/example5/ExampleScheduleRpcSnippet.java#L31)):*
> ```Java
> 
> /**
>  * Demonstrates how to schedule an RPC call.
> ```

nit: s/call

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/66)*

**Comment by l-meng** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[examples/ex5_schedule_rpc/src/main/java/com/google/android/mobly/snippet/example5/ExampleScheduleRpcSnippet.java, line 31 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/66#-Kn5ie3rsz7gc7itMaFV:-Kn5jgunTzmj-HzvBD6c:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/c6d4bfdc3d7accfe1945f3c6e15edff98a825fc9/examples/ex5_schedule_rpc/src/main/java/com/google/android/mobly/snippet/example5/ExampleScheduleRpcSnippet.java#L31)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

nit: s/call
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/66)*

**Comment by dthkao** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/66#-:-Kn5l1HLqO_M4kyqY4sV:bnfp4nl)*

**Pull request merged**
