### PR TITLE
Add all examples to top level readme and massage descriptions.

### PR DESCRIPTION
**Pull request by dthkao**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-snippet-lib/67)

### CODE REVIEW

**Comment by adorokhine** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 62 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-KnGxkmbY81GHVqiB0mm:-KnGxkmc4Pu9Ga-BmGzv:b-qrt064) ([raw file](https://github.com/google/mobly-snippet-lib/blob/021b111c25f64387febdd27863949408df1630be/README.md#L62)):*
> ```Markdown
>     UIAutomator works even without access to app source code.
> *   [ex5_schedule_rpc](examples/ex5_schedule_rpc): Example of how to use
>     the `scheduleRpc` RPC to handle RPC scheduling.
> ```

Maybe "how to use the 'scheduleRpc' RPC to execute another RPC at a later time, potentially after device disconnection"?

---

*[examples/ex1_standalone_app/README.md, line 4 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-KnGxwQjI0rLP0eJ6GUr:-KnGxwQjI0rLP0eJ6GUs:b-ynbps8) ([raw file](https://github.com/google/mobly-snippet-lib/blob/5250e7084185fc35fd6d8c6da8681b0d772c88f5/examples/ex1_standalone_app/README.md#L4)):*
> ```Markdown
> 
> This tutorial shows you how to create a standalone Mobly snippet app, which runs
> by itself and doesn't instrument a main app.
> ```

Why the removal here? I thought it was a good explanation of "standalone".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67)*

**Comment by l-meng** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[examples/ex5_schedule_rpc/README.md, line 1 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-KnH0u87YlDZwEq0PysF:-KnH0u87YlDZwEq0PysG:bi4pkj6) ([raw file](https://github.com/google/mobly-snippet-lib/blob/021b111c25f64387febdd27863949408df1630be/examples/ex5_schedule_rpc/README.md#L1)):*
> Async Event Rpc Example

This is not right :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67)*

**Comment by l-meng** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[examples/ex5_schedule_rpc/README.md, line 12 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-KnH1ExPNRii_tNGiAHh:-KnH1ExPNRii_tNGiAHi:b-79syp4) ([raw file](https://github.com/google/mobly-snippet-lib/blob/021b111c25f64387febdd27863949408df1630be/examples/ex5_schedule_rpc/README.md#L12)):*
> Monsoon starts
maybe better: "before USB got disconnected"

Not sure if it worth mentioning that "one can schedule RPC even USB is not disconnected"? but seems we can do it without schedule it, in this case

---

*[examples/ex5_schedule_rpc/README.md, line 22 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-KnH2IX2v0-hz-VVj0bn:-KnH2IX2v0-hz-VVj0bo:b-2184zx) ([raw file](https://github.com/google/mobly-snippet-lib/blob/021b111c25f64387febdd27863949408df1630be/examples/ex5_schedule_rpc/README.md#L22)):*
> ```Markdown
> 2. Start Monsoon device to collect battery data, at the same time, USB is turned off.
> 3. After 10 seconds, phone call starts while USB is off.
> 4. Finally, phonecall finished, Monsoon data collection completed and USB is turned on.
> ```

5. User can retrieve cached events, if any

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67)*

**Comment by dthkao** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 62 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-KnGxkmbY81GHVqiB0mm:-KnH8VSaeP8tn22YOOOR:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/021b111c25f64387febdd27863949408df1630be/README.md#L62)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Maybe "how to use the 'scheduleRpc' RPC to execute another RPC at a later time, potentially after device disconnection"?
</blockquote></details>

Done.

---

*[examples/ex1_standalone_app/README.md, line 4 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-KnGxwQjI0rLP0eJ6GUr:-KnH9QP35vwHYtyX1txE:b-ilore9) ([raw file](https://github.com/google/mobly-snippet-lib/blob/5250e7084185fc35fd6d8c6da8681b0d772c88f5/examples/ex1_standalone_app/README.md#L4)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Why the removal here? I thought it was a good explanation of "standalone".
</blockquote></details>

These lines have confused a few people new to Android testing. Massaged a bit more for clarity.

---

*[examples/ex5_schedule_rpc/README.md, line 1 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-KnH0u87YlDZwEq0PysF:-KnHAG05C5AQ12gcJnyW:bs7wuox) ([raw file](https://github.com/google/mobly-snippet-lib/blob/021b111c25f64387febdd27863949408df1630be/examples/ex5_schedule_rpc/README.md#L1)):*
<details><summary><i>Previously, l-meng wrote…</i></summary><blockquote>

> Async Event Rpc Example

This is not right :)
</blockquote></details>

Done.h

---

*[examples/ex5_schedule_rpc/README.md, line 12 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-KnH1ExPNRii_tNGiAHh:-KnHDEpytudJMKhprcFe:bvvond3) ([raw file](https://github.com/google/mobly-snippet-lib/blob/021b111c25f64387febdd27863949408df1630be/examples/ex5_schedule_rpc/README.md#L12)):*
<details><summary><i>Previously, l-meng wrote…</i></summary><blockquote>

> Monsoon starts
maybe better: "before USB got disconnected"

Not sure if it worth mentioning that "one can schedule RPC even USB is not disconnected"? but seems we can do it without schedule it, in this case
</blockquote></details>

revised.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67)*

**Comment by adorokhine** [comment]
Reviewed 1 of 6 files at r1, 3 of 4 files at r2.
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[examples/ex5_schedule_rpc/README.md, line 8 at r2](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-KnaLRjuhLX7izgSxrga:-KnaLRjwla5BTsg0tbCs:b-kae3ul) ([raw file](https://github.com/google/mobly-snippet-lib/blob/094ce87d67685e03163ad42bf508a177ac761b5a/examples/ex5_schedule_rpc/README.md#L8)):*
> ```Markdown
> ## Why this is needed?
> 
> Some tests may need t snippet RPC to execute when the snippet client is unable
> ```

"may need t snippet"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67)*

**Comment by dthkao** [comment]
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[examples/ex5_schedule_rpc/README.md, line 22 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-KnH2IX2v0-hz-VVj0bn:-KoVaoMEA11sK67cU65S:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/021b111c25f64387febdd27863949408df1630be/examples/ex5_schedule_rpc/README.md#L22)):*
<details><summary><i>Previously, l-meng wrote…</i></summary><blockquote>

5. User can retrieve cached events, if any
</blockquote></details>

Done.

---

*[examples/ex5_schedule_rpc/README.md, line 8 at r2](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-KnaLRjuhLX7izgSxrga:-KoVamZIjWIZ2wCK6_AQ:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/094ce87d67685e03163ad42bf508a177ac761b5a/examples/ex5_schedule_rpc/README.md#L8)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

"may need t snippet"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67)*

**Comment by dthkao** [comment]
ping

**Comment by xpconanfan** [comment]
Reviewed 1 of 6 files at r1, 2 of 4 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[examples/ex2_espresso/README.md, line 6 at r3](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-KrdEQup750kFbTgWxJJ:-KrdEQup750kFbTgWxJK:b-mgbs7s) ([raw file](https://github.com/google/mobly-snippet-lib/blob/2ab97daf06a296263b5750c95116cb2f46d06d5c/examples/ex2_espresso/README.md#L6)):*
> ```Markdown
> app using Espresso.
> 
> The same approach can be used  to create any snippet app that needs to access
> ```

Extra space before "to"?

---

*[examples/ex3_async_event/README.md, line 6 at r3](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-KrdEc1HsoVD8GVSy8de:-KrdEc1HsoVD8GVSy8df:b-dmkfj1) ([raw file](https://github.com/google/mobly-snippet-lib/blob/2ab97daf06a296263b5750c95116cb2f46d06d5c/examples/ex3_async_event/README.md#L6)):*
> ```Markdown
> to handle asynchronous callbacks.
> 
> See the source code `ExampleAsyncSnippet.java` for details.
> ```

source code "of"?

---

*[examples/ex5_schedule_rpc/README.md, line 3 at r3](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-KrdF5rQZ5UvIa-ZJCXO:-KrdF5rQZ5UvIa-ZJCXP:b-ycxnhh) ([raw file](https://github.com/google/mobly-snippet-lib/blob/2ab97daf06a296263b5750c95116cb2f46d06d5c/examples/ex5_schedule_rpc/README.md#L3)):*
> ```Markdown
> # Scheduling RPCs Example
> 
> This example shows you how to use the `scheduleRpc` RPC which is built into
> ```

How about just
"`scheduleRpc` which is..."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67)*

**Comment by dthkao** [comment]
Review status: 3 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

*[examples/ex2_espresso/README.md, line 6 at r3](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-KrdEQup750kFbTgWxJJ:-KrdHltn9iBLW79z84OP:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/2ab97daf06a296263b5750c95116cb2f46d06d5c/examples/ex2_espresso/README.md#L6)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

Extra space before "to"?
</blockquote></details>

Done.

---

*[examples/ex3_async_event/README.md, line 6 at r3](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-KrdEc1HsoVD8GVSy8de:-KrdHv9D3ERJzRGk7Rv2:b-nssx0s) ([raw file](https://github.com/google/mobly-snippet-lib/blob/2ab97daf06a296263b5750c95116cb2f46d06d5c/examples/ex3_async_event/README.md#L6)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

source code "of"?
</blockquote></details>

Done. "in"

---

*[examples/ex5_schedule_rpc/README.md, line 3 at r3](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-KrdF5rQZ5UvIa-ZJCXO:-KrdIFfZ0f4EfTH0jumZ:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/2ab97daf06a296263b5750c95116cb2f46d06d5c/examples/ex5_schedule_rpc/README.md#L3)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

How about just
"`scheduleRpc` which is..."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67)*

**Comment by xpconanfan** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/67#-:-KrdJF6HHyx2JQYhZOp0:bnfp4nl)*

**Pull request merged**
