### PR TITLE
update gradle and linting

### PR DESCRIPTION
**Pull request by dthkao**
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-snippet-lib/65)

### CODE REVIEW

**Comment by adorokhine** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[third_party/sl4a/build.gradle, line 19 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/65#-Kn5hIXGXFkLPsMZ8ALM:-Kn5hIXHus9_PgBXjdE2:bexx9ea) ([raw file](https://github.com/google/mobly-snippet-lib/blob/da6c05c03ca6fe43dacf1a4866dd2ecdfae170ad/third_party/sl4a/build.gradle#L19)):*
> ```Gradle
> apply plugin: 'com.github.dcendents.android-maven'
> 
> allprojects {
> ```

Does allprojects have effect here or does it have to be in the root project's build.gradle?

---

*[third_party/sl4a/build.gradle, line 41 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/65#-Kn5hD2Rkrf26c8E51SE:-Kn5hD2S6-HaGtP3CMCJ:bz62sf1) ([raw file](https://github.com/google/mobly-snippet-lib/blob/da6c05c03ca6fe43dacf1a4866dd2ecdfae170ad/third_party/sl4a/build.gradle#L41)):*
> ```Gradle
>         project.version = VERSION_NAME
>     }
>     lintOptions {
> ```

I don't think this would apply to the examples, would it? Not that familiar with gradle; is there anywhere we can stick this that would apply it everywhere? There might not be :/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/65)*

**Comment by dthkao** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[third_party/sl4a/build.gradle, line 19 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/65#-Kn5hIXGXFkLPsMZ8ALM:-Kn6j2qbVVWFv4zDnEiR:bphhard) ([raw file](https://github.com/google/mobly-snippet-lib/blob/da6c05c03ca6fe43dacf1a4866dd2ecdfae170ad/third_party/sl4a/build.gradle#L19)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Does allprojects have effect here or does it have to be in the root project's build.gradle?
</blockquote></details>

It's actually already in the project root! whoops. reverting this one.

---

*[third_party/sl4a/build.gradle, line 41 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/65#-Kn5hD2Rkrf26c8E51SE:-Kn6jmQ0hhT_nJggwllg:b-f3qak8) ([raw file](https://github.com/google/mobly-snippet-lib/blob/da6c05c03ca6fe43dacf1a4866dd2ecdfae170ad/third_party/sl4a/build.gradle#L41)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

I don't think this would apply to the examples, would it? Not that familiar with gradle; is there anywhere we can stick this that would apply it everywhere? There might not be :/
</blockquote></details>

I don't think so. I can add to the examples if we like?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/65)*

**Comment by adorokhine** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[third_party/sl4a/build.gradle, line 41 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/65#-Kn5hD2Rkrf26c8E51SE:-Kn6kxz_c11IeBHWLsj6:b-n5nchs) ([raw file](https://github.com/google/mobly-snippet-lib/blob/da6c05c03ca6fe43dacf1a4866dd2ecdfae170ad/third_party/sl4a/build.gradle#L41)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

I don't think so. I can add to the examples if we like?
</blockquote></details>

Sure, let's add it to the examples.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/65)*

**Comment by dthkao** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[third_party/sl4a/build.gradle, line 41 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/65#-Kn5hD2Rkrf26c8E51SE:-Kn6lqkEywsbP-Ne2FOE:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/da6c05c03ca6fe43dacf1a4866dd2ecdfae170ad/third_party/sl4a/build.gradle#L41)):*
<details><summary><i>Previously, adorokhine (Alexander Dorokhine) wrote…</i></summary><blockquote>

Sure, let's add it to the examples.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/65)*

**Comment by adorokhine** [comment]
:lgtm:

---

Reviewed 2 of 8 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/65#-:-Kn6nVCH_svaaikXWCVy:bnfp4nl)*

**Pull request merged**
