### PR TITLE
Remove an error message check that may return null. This will expose …

### PR DESCRIPTION
**Pull request by dthkao**
…an unknown error that results from not having declared INTERNET permissions

---
This change is [Reviewable](https://reviewable.io/reviews/google/mobly-snippet-lib/68)

### CODE REVIEW

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[third_party/sl4a/src/main/java/com/google/android/mobly/snippet/SnippetRunner.java, line 141 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/68#-KrX5xf5AOQzk3LoQcpO:-KrX5xf6z7va0WFG-i2u:b-iuwshk) ([raw file](https://github.com/google/mobly-snippet-lib/blob/5250e7084185fc35fd6d8c6da8681b0d772c88f5/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/SnippetRunner.java#L141)):*
> ```Java
>             androidProxy.startLocal(port);
>         } catch (SocketException e) {
>             if (e.getMessage().equals("Permission denied")) {
> ```

wouldn't this mistakenly present all SocketException as a potential permission error?

An easy fix is to change the comparison line to:
`"Permission denied".equals(e.getMessage())`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/68)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[third_party/sl4a/src/main/java/com/google/android/mobly/snippet/SnippetRunner.java, line 141 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/68#-KrX5xf5AOQzk3LoQcpO:-KrdVuxiDRABFfDUTAVJ:b6vzkt7) ([raw file](https://github.com/google/mobly-snippet-lib/blob/5250e7084185fc35fd6d8c6da8681b0d772c88f5/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/SnippetRunner.java#L141)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

wouldn't this mistakenly present all SocketException as a potential permission error?

An easy fix is to change the comparison line to:
`"Permission denied".equals(e.getMessage())`
</blockquote></details>

That'd result in an NPE? and hide the exception still.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/68)*

**Comment by xpconanfan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[third_party/sl4a/src/main/java/com/google/android/mobly/snippet/SnippetRunner.java, line 141 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/68#-KrX5xf5AOQzk3LoQcpO:-KrgLUSJG38pN6-Is6hE:b-fq3h3t) ([raw file](https://github.com/google/mobly-snippet-lib/blob/5250e7084185fc35fd6d8c6da8681b0d772c88f5/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/SnippetRunner.java#L141)):*
<details><summary><i>Previously, dthkao (David T.H. Kao) wrote…</i></summary><blockquote>

That'd result in an NPE? and hide the exception still.
</blockquote></details>

The NPE came from `e.getMessage()` returns null, so flipping the order should work?
Or are we seeing that `e` is null? Is that possible...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/68)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[third_party/sl4a/src/main/java/com/google/android/mobly/snippet/SnippetRunner.java, line 141 at r1](https://reviewable.io:443/reviews/google/mobly-snippet-lib/68#-KrX5xf5AOQzk3LoQcpO:-KrgObvHXcRfTD6Wb297:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/5250e7084185fc35fd6d8c6da8681b0d772c88f5/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/SnippetRunner.java#L141)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

The NPE came from `e.getMessage()` returns null, so flipping the order should work?
Or are we seeing that `e` is null? Is that possible...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/68)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/68#-:-KrgOk5zPOL4C7pOF4GG:bnfp4nl)*

**Comment by xpconanfan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[third_party/sl4a/src/main/java/com/google/android/mobly/snippet/SnippetRunner.java, line 142 at r2](https://reviewable.io:443/reviews/google/mobly-snippet-lib/68#-KrgOltnUd5sp5k-8bkh:-KrgOltnUd5sp5k-8bki:b2nicts) ([raw file](https://github.com/google/mobly-snippet-lib/blob/ff015dd699fbefe7f19554a1d6b3a105dd7cec1c/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/SnippetRunner.java#L142)):*
> ```Java
>         } catch (SocketException e) {
>             if ("Permission denied".equals(e.getMessage())) {
> 	        throw new RuntimeException(
> ```

tab

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/68)*

**Comment by dthkao** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[third_party/sl4a/src/main/java/com/google/android/mobly/snippet/SnippetRunner.java, line 142 at r2](https://reviewable.io:443/reviews/google/mobly-snippet-lib/68#-KrgOltnUd5sp5k-8bkh:-KrgP7Fu86nzwIL-oevc:b-896fix) ([raw file](https://github.com/google/mobly-snippet-lib/blob/ff015dd699fbefe7f19554a1d6b3a105dd7cec1c/third_party/sl4a/src/main/java/com/google/android/mobly/snippet/SnippetRunner.java#L142)):*
<details><summary><i>Previously, xpconanfan (Ang Li) wrote…</i></summary><blockquote>

tab
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/68)*

**Comment by xpconanfan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/68)*

**Comment by xpconanfan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/mobly-snippet-lib/68#-:-KrgPLjJkE1fqIjwo8ft:bnfp4nl)*

**Pull request merged**
